const fs = require('fs');
const path = require('path');

const {
  FACTORY_PATHS,
  getValidationErrors,
  readJson,
  validateFactoryProject
} = require('./validate-factory');

const ROOT_DIR = path.resolve(__dirname, '..', '..');
const DEFAULT_CONTEXT_PATH = path.join(ROOT_DIR, 'docs', 'factory', 'PROJECT_CONTEXT.md');

function hasCapability(project, id) {
  const enabled = Array.isArray(project.capabilities?.enabled)
    ? project.capabilities.enabled
    : [];

  return enabled.includes(id);
}

function yesNo(value) {
  return value ? 'YES' : 'NO';
}

function inlineValue(value) {
  return String(value).replace(/\s+/g, ' ').trim();
}

function nullableValue(value) {
  return typeof value === 'string' && value.trim() !== ''
    ? inlineValue(value)
    : 'Not configured';
}

function urlValue(value) {
  return typeof value === 'string' && value.trim() !== ''
    ? `<${value}>`
    : 'Not configured';
}

function generateProjectContext(project) {
  const languages = Array.isArray(project.wordpress?.languages)
    ? project.wordpress.languages
    : [];
  const multilingualWithoutPolylang = languages.length > 1
    && !hasCapability(project, 'polylang');
  const lines = [
    '# MWStudios Project Context',
    '',
    '> Auto-generated from `factory/project.json` by `npm run factory:context`.',
    '> Do not edit this file manually.',
    '',
    '## Project',
    '',
    `Name: ${inlineValue(project.project.name)}`,
    `Slug: ${inlineValue(project.project.slug)}`,
    `Theme name: ${inlineValue(project.project.themeName)}`,
    `Text domain: ${inlineValue(project.project.textDomain)}`,
    `PHP prefix: ${inlineValue(project.project.prefix)}`,
    `Mode: ${inlineValue(project.mode)}`,
    '',
    '## Environment',
    '',
    `Local URL: ${urlValue(project.environment.localUrl)}`,
    `Production URL: ${urlValue(project.environment.productionUrl)}`,
    '',
    '## Design',
    '',
    `Figma design: ${urlValue(project.figma.url)}`,
    `Figma page: ${nullableValue(project.figma.page)}`,
    `Figma root/start node: ${nullableValue(project.figma.rootNode)}`,
    '',
    '## Languages',
    '',
    `Default: ${inlineValue(project.wordpress.defaultLanguage)}`,
    `Enabled: ${languages.map(inlineValue).join(', ')}`,
    '',
    '## WordPress',
    '',
    `ACF Pro: ${yesNo(project.wordpress.acfPro)}`,
    `Contact Form 7: ${yesNo(hasCapability(project, 'cf7'))}`,
    `Polylang: ${yesNo(hasCapability(project, 'polylang'))}`,
    `WooCommerce: ${yesNo(hasCapability(project, 'woocommerce'))}`,
    `Google Maps: ${yesNo(hasCapability(project, 'google-maps'))}`,
    '',
    '## Frontend',
    '',
    `Swiper: ${yesNo(hasCapability(project, 'swiper'))}`,
    `AOS: ${yesNo(hasCapability(project, 'aos'))}`,
    `Lenis smooth scroll: ${yesNo(hasCapability(project, 'lenis'))}`,
    '',
    '## Features',
    '',
    `Blog/news: ${yesNo(hasCapability(project, 'blog'))}`,
    `Topbar: ${yesNo(hasCapability(project, 'topbar'))}`,
    `Promo popup: ${yesNo(hasCapability(project, 'promo-popup'))}`,
    '',
    '## Build',
    '',
    `Distribution strategy: ${inlineValue(project.build.distStrategy)}`,
    'Release includes `dist/`, `src/`, and `vendor/`; it excludes `node_modules/` and `.git/`.',
    '',
    '## Implementation Rules',
    '',
    '- Implement the supplied Figma design 1:1.',
    '- Preserve the existing boilerplate architecture.',
    '- Inspect existing components and utilities before creating new ones.',
    '- Reuse the existing grid, spacing, helpers, and partials.',
    '- Do not remove unused boilerplate functionality merely because this project does not use it.',
    '- `project.json` describes project requirements, not modules to physically delete from the boilerplate.',
    '- Plan ACF before implementing content-heavy sections.',
    '- Use classic PHP templates, ACF, SCSS, and vanilla JavaScript.',
    '- Do not introduce React or Tailwind into the final WordPress theme.'
  ];

  if (multilingualWithoutPolylang) {
    lines.push(
      '',
      '## Configuration Note',
      '',
      'Multiple languages are enabled without Polylang. Confirm the multilingual implementation strategy before coding.'
    );
  }

  return `${lines.join('\n')}\n`;
}

function assertValidProject(project) {
  const errors = getValidationErrors(validateFactoryProject(project));

  if (errors.length > 0) {
    throw new Error(`Cannot generate project context:\n- ${errors.join('\n- ')}`);
  }
}

function writeProjectContext({
  project = readJson(FACTORY_PATHS.project),
  outputPath = DEFAULT_CONTEXT_PATH
} = {}) {
  assertValidProject(project);
  const content = generateProjectContext(project);

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, 'utf8');

  return outputPath;
}

function main() {
  try {
    const outputPath = writeProjectContext();
    console.log(`Project context generated: ${path.relative(ROOT_DIR, outputPath)}`);
  } catch (error) {
    console.error(`Project context generation failed: ${error.message}`);
    process.exitCode = 1;
  }
}

if (require.main === module) {
  main();
}

module.exports = {
  DEFAULT_CONTEXT_PATH,
  generateProjectContext,
  hasCapability,
  writeProjectContext
};
