/** Offline source -> editable migration data. No production requests or scripts. */
const fs=require('fs'),path=require('path');
const {discoverBrowser,getChromium}=require('../../../factory/qa/browser');
const {verify,sha}=require('../../../../tools/live-capture/bundle');
const config=require('../../../../docs/projects/collegium-balticum/live.json');
const evidence=require('../../../../docs/projects/collegium-balticum/capture-3c/references-evidence.json');
const root=path.resolve(__dirname,'../../../..'),output=path.join(root,'.factory-cache/live/collegium-balticum/migration');
async function main(){fs.mkdirSync(output,{recursive:true});const assets=new Map(),bundles=new Set(evidence.rows.flatMap(r=>r.views.map(v=>v.bundle)));for(const bundle of bundles){const base=path.join(root,'.factory-cache/live/collegium-balticum/imports',bundle);verify(base,config);const m=JSON.parse(fs.readFileSync(path.join(base,'manifest.json')));for(const file of m.files.filter(f=>f.path.endsWith('resources.json'))){const r=JSON.parse(fs.readFileSync(path.join(base,file.path)));for(const a of r.assets||[]){if(a.file&&!a.error)assets.set(a.url,{...a,path:path.join(base,a.file)});}}}
const browser=await getChromium().launch({executablePath:discoverBrowser().browser.executablePath,headless:true,args:['--no-sandbox']});const page=await browser.newPage();await page.route('**/*',r=>r.abort());const pages=[];const cssUsed=new Set();
for(const row of evidence.rows){const view=row.views[0],dom=JSON.parse(fs.readFileSync(view.paths.dom));await page.setContent(fs.readFileSync(view.paths.html,'utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<link\b[^>]*>/gi,''),{waitUntil:'domcontentloaded'});
const data=await page.evaluate(({id,dom})=>{
const clean=e=>{e=e.cloneNode(true);e.querySelectorAll('script,style,noscript,link,.slick-cloned,.bx-clone,.bx-controls,.slick-arrow,.mask,.wpcf7-response-output,.wpcf7-spinner,.hidden-fields-container').forEach(n=>n.remove());
for(const n of [e,...e.querySelectorAll('*')]){const lazy=n.getAttribute('nitro-lazy-src')||n.getAttribute('data-src');const iframeSource=n.getAttribute('nitro-og-src');for(const a of [...n.attributes])if(/^on/i.test(a.name)||/^nitro|^data-nitro|^data-srcset|^data-src$|^data-lazy|^aria-hidden$|^tabindex$/.test(a.name))n.removeAttribute(a.name);n.className=typeof n.className==='string'?n.className.split(/\s+/).filter(c=>c&&!/^(nitro-|wow$|fadeIn|animated$|slick-(initialized|slider|slide|current|active)$|lazyloaded|wp-container-|wp-elements-)/.test(c)).map(c=>c==='container'?'l-container':c).join(' '):n.className;
if(n.hasAttribute('style')){const keep=[...n.style].filter(p=>!['width','height','float','position','transform','transition-duration','visibility','animation-name','list-style','left','top','display','opacity'].includes(p));const values=keep.map(p=>p+':'+n.style.getPropertyValue(p)).join(';');values?n.setAttribute('style',values):n.removeAttribute('style');}
if(n.tagName==='IMG'){const url=n.getAttribute('src')||'';if(!url||url.startsWith('data:')){const original=lazy;if(original)n.setAttribute('src',original);else{n.remove();continue;}}n.removeAttribute('srcset');n.removeAttribute('sizes');n.setAttribute('data-cb-image',n.getAttribute('src'));}
if(n.tagName==='A'){const u=n.getAttribute('href')||'';if(u.startsWith('javascript:'))n.removeAttribute('href');if(n.target==='_blank')n.setAttribute('rel','noopener noreferrer');if(u.startsWith('tel:'))n.setAttribute('href','tel:'+u.slice(4).replace(/[^+\d]/g,''));}
if(n.tagName==='IFRAME'){const current=n.getAttribute('src')||'';const u=current.startsWith('https://')?current:iframeSource||lazy||'';if(!u.startsWith('https://')){n.remove();continue;}n.setAttribute('src',u.replace(/([?&])autoplay=1(&|$)/,'$1autoplay=0$2'));n.setAttribute('title',n.title||e.querySelector('h1,h2,h3')?.textContent.trim()||'Materiał multimedialny');n.setAttribute('loading','lazy');}
}
for(const wrapper of [...e.querySelectorAll('.slick-track,.slick-list,.bx-viewport,.bx-wrapper')].reverse())wrapper.replaceWith(...wrapper.childNodes);
e.querySelectorAll('p,li,h1,h2,h3,h4,h5,h6').forEach(n=>{if(!n.textContent.trim()&&!n.querySelector('img,iframe,video,input,button,textarea,select')){if(n.tagName==='P'&&n.textContent.includes('\u00a0')&&n.parentElement!==e)n.setAttribute('aria-hidden','true');else n.remove();}});return e;};
let leadingSpace=0;const sections=[];const source=document.querySelector('main');
for(const original of [...source.children]){let n=clean(original);if(n.classList.contains('wp-block-spacer')){if(!sections.length)leadingSpace+=Math.min(200,parseFloat(original.style.height)||0);if(sections.length)sections.at(-1).space_after=Math.min(200,parseFloat(original.style.height)||0);continue;}if(!n.textContent.trim()&&!n.querySelector('img,iframe,video'))continue;
const entry={acf_fc_layout:'content',label:n.querySelector('h1,h2,h3')?.textContent.trim().slice(0,100)||n.className.split(' ')[0]||'Treść',variant:n.className,tag:n.tagName.toLowerCase(),body:n.innerHTML};
if(n.classList.contains('banner-slider')){entry.acf_fc_layout='banner';entry.items=[...n.querySelectorAll('.bx-slider > .box')].map(box=>({body:box.innerHTML}));if(!entry.items.length)entry.items=[{body:n.innerHTML}];entry.body='';}
else if(n.classList.contains('slider')||n.classList.contains('promotion')||n.classList.contains('partners')){entry.acf_fc_layout='carousel';const tracks=[...n.querySelectorAll('.global-slider,.global-slider-test,.logo-slider,.part-slider')];entry.groups=tracks.map((track,i)=>({title:n.querySelectorAll('.categories a')[i]?.textContent.trim()||'',variant:track.className,target:track.getAttribute('data-target')||'',items:[...track.children].map(box=>({body:box.outerHTML}))}));entry.body=n.innerHTML;for(const track of n.querySelectorAll('.global-slider,.global-slider-test,.logo-slider,.part-slider'))track.innerHTML='';entry.shell=n.innerHTML;}
else if(n.classList.contains('faq')){entry.acf_fc_layout='accordion';const heading=n.querySelector(':scope>.l-container>.section-title,:scope>.section-title')?.cloneNode(true);heading?.querySelectorAll('.faq-content,.questions,.question').forEach(n=>n.remove());entry.title=heading?.innerHTML||'';entry.items=[...n.querySelectorAll('.question')].map(q=>({title:q.querySelector(':scope>.title')?.innerHTML||'',body:q.querySelector(':scope>.hide')?.innerHTML||q.querySelector(':scope>.content')?.innerHTML||''}));entry.body='';}
else if(n.classList.contains('wp-block-getwid-accordion')){entry.acf_fc_layout='accordion';entry.items=[...n.querySelectorAll('.wp-block-getwid-accordion__header')].map(h=>({title:h.textContent.trim(),body:h.parentElement.nextElementSibling?.innerHTML||'',initially_open:dom.images.some(i=>i.height>0&&i.y>0&&(h.parentElement.nextElementSibling?.innerHTML||'').includes(i.url))}));entry.body='';}
else if(n.classList.contains('text-tabs')){entry.acf_fc_layout='tabs';}
if(n.classList.contains('banner') && !n.querySelector('.text')?.textContent.trim())entry.variant+=' banner--image-only';
sections.push(entry);}
const menu=ul=>[...ul.children].filter(n=>n.tagName==='LI').map(li=>{const a=li.querySelector(':scope>a');return{title_html:a?.innerHTML||'',classes:li.className.split(/\s+/).filter(c=>['mobileOnly','orange','default-button'].includes(c)),title:a?.textContent.trim()||'',url:a?.getAttribute('href')||'',icon:a?.querySelector('i')?.className||'',children:li.querySelector(':scope>ul')?menu(li.querySelector(':scope>ul')):[]}});
const header=document.querySelector('body>header')||document.querySelector('header.homepage');
const footer=document.querySelector('body>footer')||document.querySelector('footer');
const headerClean=header?clean(header):null,footerClean=footer?clean(footer):null;
const mainMenu=header?.querySelector('.main-menu ul');const logo=header?.querySelector('a img');
const cards=[...source.querySelectorAll('.slider .box,.posts-listing .box,.posts-listing article')].filter(n=>!n.closest('.slick-cloned')).map(n=>({title:n.getAttribute('title')||n.querySelector('.title,h2,h3')?.textContent.trim()||'',url:(n.matches('a')?n:n.querySelector('a[href*="/wpisy/"]'))?.href||'',image:n.querySelector('img')?.getAttribute('src')||'',alt:n.querySelector('img')?.getAttribute('alt'),excerpt:n.querySelector('.desc,.description')?.innerHTML||'',date:n.querySelector('time,.date')?.textContent.trim()||'',html:clean(n).outerHTML})).filter(c=>c.title&&c.url);
return{embedInventory:[...source.querySelectorAll('iframe')].map(n=>n.getAttribute('nitro-og-src')||n.getAttribute('src')).filter(u=>u?.startsWith('https://')).map(u=>u.replace(/([?&])autoplay=1(&|$)/,'$1autoplay=0$2')),leadingSpace,breadcrumb:header?.querySelector('.breadcrumbs')?clean(header.querySelector('.breadcrumbs')).outerHTML:'',contentBlocks:[...clean(source).querySelectorAll('h1,h2,h3,h4,h5,h6,p,li,td,figcaption')].map(n=>n.textContent.replace(/\s+/g,' ').trim()).filter(t=>t.length>8),inlineStyles:[...document.querySelectorAll('style')].filter(n=>!n.id.startsWith('nitro')&&!/onetap|NPRL/.test(n.textContent)).map(n=>n.textContent),sections,mainClass:source.className.replace(/nitro-\S+/g,''),title:dom.headings.find(h=>h.tag==='H1')?.text||dom.title.split(' » ')[0],seo:dom.seo,canonical:dom.canonical,seoTitle:dom.title,headingInventory:dom.headings.map(h=>({tag:h.tag,text:h.text})),menu:mainMenu?menu(mainMenu):[],header:headerClean?.innerHTML||'',footer:footerClean?.innerHTML||'',logo:logo?.getAttribute('src')||'',cards,text:source.textContent.trim(),html:clean(source).innerHTML};
},{id:row.id,dom});for(const section of data.sections.filter(s=>s.acf_fc_layout==='carousel')){const rectangle=dom.sections.find(r=>section.variant.split(/\s+/).filter(Boolean).every(c=>r.classes?.split(/\s+/).includes(c)));if(rectangle){const image=dom.images.filter(i=>i.x>=0&&i.x<1440&&i.y>=rectangle.y&&i.y<rectangle.y+rectangle.height&&i.width>100).sort((a,b)=>a.x-b.x)[0];for(const group of section.groups){const index=group.items.findIndex(i=>i.body.includes(image?.url||'__none__'));if(index>0)group.items=[...group.items.slice(index),...group.items.slice(0,index)];}}}
for(const section of data.sections.filter(s=>s.acf_fc_layout==='banner')){for(const [name,viewIndex,width] of [['desktop',0,1440],['mobile',1,390]]){const d=JSON.parse(fs.readFileSync(row.views[viewIndex].paths.dom));const visible=d.images.find(i=>i.x>=0&&i.x<width&&i.y>=0&&i.y<900&&i.width>width/2);section['initial_'+name]=Math.max(0,section.items.findIndex(i=>i.body.includes(visible?.url||'__none__')));}}
pages.push({id:row.id,url:row.url,path:new URL(row.url).pathname,...data});console.log(row.id,data.sections.length,'sections');}
await browser.close();const supplemental=path.join(output,'supplemental-assets.json');if(fs.existsSync(supplemental))for(const a of JSON.parse(fs.readFileSync(supplemental))){if(sha(fs.readFileSync(a.path))!==a.sha256)throw Error('Supplemental hash mismatch');assets.set(a.url,a);}
const migration={source:'verified-3c',configHash:sha(Buffer.from(JSON.stringify(config))),assets:[...assets.values()],pages};fs.writeFileSync(path.join(output,'source.json'),JSON.stringify(migration,null,2)+'\n');console.log(path.join(output,'source.json'));
const documentSource=require('../../../../docs/projects/collegium-balticum/documents-source.json');
const documentPath=path.join(output,'documents.json'),previousDocuments=fs.existsSync(documentPath)?JSON.parse(fs.readFileSync(documentPath)).flatMap(p=>p.documents):[];
const documents=pages.map(p=>({id:p.id,documents:documentSource.documents.flatMap(d=>d.occurrences.filter(o=>o.id===p.id).map(o=>previousDocuments.find(old=>old.url===d.url&&old.localCopy==='DONE')||{url:d.url,label:o.label,status:'SOURCE_LINK_PRESERVED',localCopy:'BLOCKED',reason:'Plik nie występuje w artefakcie; brak połączenia do hosta CB z Codespace udokumentowano w 3B-0.'}))}));
fs.writeFileSync(documentPath,JSON.stringify(documents,null,2)+'\n');
}
if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1});
