<?php
/** Run with npm run cb:wp -- eval-file <theme>/scripts/projects/collegium-balticum/migrate/import.php */
if(!defined('WP_CLI'))exit;
$theme=get_stylesheet_directory();$cache=$theme.'/.factory-cache/live/collegium-balticum/migration';
$data=json_decode(file_get_contents($cache.'/source.json'),true,512,JSON_THROW_ON_ERROR);
require_once ABSPATH.'wp-admin/includes/image.php';
$assets=[];$missing=[];$ids=[];$urlmap=[];
add_filter('upload_mimes',function($m){$m['svg']='image/svg+xml';return $m;});
add_filter('intermediate_image_sizes_advanced',function(){return [];}); // Preserve originals; captured crops are separate originals.
foreach($data['assets'] as $asset){if($asset['type']!=='image'||!preg_match('~(?:nitrocdn\.com|cb\.szczecin\.pl)~',$asset['url']))continue;
    $file=str_replace('/workspace',$theme,$asset['path']);if(!is_file($file)||hash_file('sha256',$file)!==$asset['sha256'])throw new RuntimeException('Asset hash mismatch: '.$asset['url']);
    $existing=get_posts(['post_type'=>'attachment','post_status'=>'inherit','meta_key'=>'_cb_sha256','meta_value'=>$asset['sha256'],'numberposts'=>1]);
    if($existing)$id=$existing[0]->ID;else{
        $mime=explode(';',$asset['contentType'])[0];$ext=['image/webp'=>'webp','image/jpeg'=>'jpg','image/png'=>'png','image/svg+xml'=>'svg','image/gif'=>'gif','image/avif'=>'avif'][$mime]??null;if(!$ext){$missing[]=['url'=>$asset['url'],'reason'=>'unsupported MIME'];continue;}
        $name=sanitize_file_name(pathinfo(wp_parse_url($asset['url'],PHP_URL_PATH),PATHINFO_FILENAME)).'-'.substr($asset['sha256'],0,10).'.'.$ext;
        $bytes=file_get_contents($file);if($ext==='svg'){
            $xml=new DOMDocument();libxml_use_internal_errors(true);if(!$xml->loadXML($bytes,LIBXML_NONET))throw new RuntimeException('Invalid SVG');
            $xp=new DOMXPath($xml);foreach($xp->query('//*[local-name()="script" or local-name()="foreignObject"]') as $node)$node->parentNode->removeChild($node);
            foreach($xp->query('//*') as $node)foreach(iterator_to_array($node->attributes) as $attr)if(preg_match('/^on/i',$attr->name)||preg_match('/javascript:/i',$attr->value))$node->removeAttribute($attr->name);$bytes=$xml->saveXML();
        }
        $upload=wp_upload_bits($name,null,$bytes);if($upload['error'])throw new RuntimeException($upload['error']);
        $id=wp_insert_attachment(['post_title'=>pathinfo($name,PATHINFO_FILENAME),'post_mime_type'=>$mime,'post_status'=>'inherit'],$upload['file']);
        if(is_wp_error($id))throw new RuntimeException($id->get_error_message());
        wp_update_attachment_metadata($id,wp_generate_attachment_metadata($id,$upload['file']));update_post_meta($id,'_cb_sha256',$asset['sha256']);update_post_meta($id,'_cb_source_url',$asset['url']);
    }
    $assets[$asset['url']]=['id'=>$id,'sha256'=>$asset['sha256']];
}
update_option('cb_asset_map',$assets,false);$GLOBALS['cb_import_assets']=$assets;$GLOBALS['cb_import_missing']=[];
function cb_import_record($source,$type,$slug,$title,$parent=0){$found=get_posts(['post_type'=>$type,'post_status'=>'any','meta_key'=>'_cb_source_url','meta_value'=>$source,'numberposts'=>1]);$id=wp_insert_post(['ID'=>$found?$found[0]->ID:0,'post_type'=>$type,'post_status'=>'publish','post_name'=>$slug,'post_title'=>$title,'post_parent'=>$parent],true);if(is_wp_error($id))throw new RuntimeException($id->get_error_message());update_post_meta($id,'_cb_source_url',$source);return $id;}
$parents=[];$template=['CB-00'=>'template-homepage.php','CB-01'=>'template-contact.php','CB-04'=>'template-banner-tile.php','CB-05'=>'template-banner-tile.php','CB-06'=>'template-banner-accordion.php','CB-07'=>'template-banner-accordion.php','CB-08'=>'template-course.php','CB-11'=>'template-course.php','CB-13'=>'template-basic.php','CB-14'=>'template-basic.php','CB-18'=>'template-basic.php'];
$root=wp_insert_term('Wpisy','category',['slug'=>'wpisy']);$root=is_wp_error($root)?get_term_by('slug','wpisy','category')->term_id:$root['term_id'];
$blog=wp_insert_term('Blog','category',['slug'=>'blog-post','parent'=>$root]);$blog=is_wp_error($blog)?get_term_by('slug','blog-post','category')->term_id:$blog['term_id'];
$urlmap['/category/wpisy/blog-post/']=['type'=>'category','id'=>$blog];$urlmap['/category/wpisy/']=['type'=>'category','id'=>$root];
foreach($data['pages'] as $p){if($p['id']==='CB-02'){$ids[$p['id']]=$blog;continue;}
    $parts=explode('/',trim($p['path'],'/'));$slug=array_pop($parts)?:'cb-home';$parent=0;$prefix='';
    if($p['id']!=='CB-03')foreach($parts as $segment){$prefix.='/'.$segment;if(!isset($parents[$prefix])){$parents[$prefix]=cb_import_record('https://www.cb.szczecin.pl'.$prefix.'/','page',$segment,ucfirst(str_replace('-',' ',$segment)),$parent);update_post_meta($parents[$prefix],'_cb_structure_only',1);} $parent=$parents[$prefix];}
    $id=cb_import_record($p['url'],$p['id']==='CB-03'?'post':'page',$slug,$p['title'],$parent);$ids[$p['id']]=$id;$urlmap[$p['path']]=['type'=>$p['id']==='CB-03'?'post':'page','id'=>$id];update_post_meta($id,'_cb_source_id',$p['id']);delete_post_meta($id,'_cb_structure_only');update_post_meta($id,'_cb_main_class',$p['mainClass']);update_post_meta($id,'_wp_page_template',$template[$p['id']]??'template-flexible.php');
    if($p['id']==='CB-03')wp_set_post_categories($id,[$blog]);
}
update_option('cb_url_map',$urlmap,false);
function cb_import_html($html){$assets=$GLOBALS['cb_import_assets'];$missing=&$GLOBALS['cb_import_missing'];
    if(!$html)return '';
    $doc=new DOMDocument();libxml_use_internal_errors(true);$doc->loadHTML('<?xml encoding="UTF-8"><div id="cb-import-root">'.$html.'</div>',LIBXML_HTML_NODEFDTD|LIBXML_HTML_NOIMPLIED|LIBXML_NONET);$xp=new DOMXPath($doc);
    foreach($xp->query('//img') as $img){$url=$img->getAttribute('data-cb-image')?:$img->getAttribute('src');$entry=$assets[$url]??null;
        if(!$entry){$basename=basename(wp_parse_url($url,PHP_URL_PATH));foreach($assets as $candidate=>$value)if(basename(wp_parse_url($candidate,PHP_URL_PATH))===$basename){$entry=$value;break;}}
        if(!$entry){$base=preg_replace('/-\d+x\d+(?=\.[^.]+$)/','',basename(wp_parse_url($url,PHP_URL_PATH)));foreach($assets as $candidate=>$value)if(preg_replace('/-\d+x\d+(?=\.[^.]+$)/','',basename(wp_parse_url($candidate,PHP_URL_PATH)))===$base){$entry=$value;break;}}
        if(!$entry){$missing[]=['url'=>$url,'reason'=>'image not present in verified assets'];continue;}
        $id=$entry['id'];$alt=$img->getAttribute('alt');if(!$img->hasAttribute('alt'))$img->setAttribute('alt','');if($alt==='' && $img->parentNode->nodeName==='a' && preg_match('/\.(?:jpg|png|webp|jpeg)(?:\?|$)/i',$img->parentNode->getAttribute('href'))){$alt='Powiększ zdjęcie w galerii';$img->setAttribute('alt',$alt);update_post_meta($id,'_cb_accessibility_alt_added',1);}if($alt!=='')update_post_meta($id,'_wp_attachment_image_alt',$alt);$img->setAttribute('src',wp_get_attachment_url($id));$img->setAttribute('class',trim(preg_replace('/\bwp-image-\d+\b/','',$img->getAttribute('class')).' wp-image-'.$id));$img->setAttribute('data-cb-attachment',(string)$id);$img->removeAttribute('data-cb-image');$img->removeAttribute('id');$img->setAttribute('loading','eager');$meta=wp_get_attachment_metadata($id);if(!empty($meta['width'])&&!$img->hasAttribute('width')){$img->setAttribute('width',$meta['width']);$img->setAttribute('height',$meta['height']);}
    }
    foreach($xp->query('//a[@href]') as $link){if(!trim($link->textContent)&&!$link->getAttribute('aria-label')){$host=wp_parse_url($link->getAttribute('href'),PHP_URL_HOST);foreach(['facebook'=>'Facebook','instagram'=>'Instagram','linkedin'=>'LinkedIn','youtube'=>'YouTube','twitter'=>'X','x.com'=>'X'] as $part=>$name)if(strpos((string)$host,$part)!==false)$link->setAttribute('aria-label',$name);}if($link->getAttribute('target')==='_blank'){$label=$link->getAttribute('aria-label')?:trim($link->textContent);if($label)$link->setAttribute('aria-label',$label.' (otwiera nową kartę)');}}
    foreach($xp->query('//a[@href]') as $anchor){$url=$anchor->getAttribute('href');if(preg_match('/\.(?:jpg|jpeg|png|webp|svg)(?:\?|$)/i',$url)){foreach($assets as $source=>$entry)if(preg_replace('/-\d+x\d+(?=\.[^.]+$)/','',basename(wp_parse_url($source,PHP_URL_PATH)))===preg_replace('/-\d+x\d+(?=\.[^.]+$)/','',basename(wp_parse_url($url,PHP_URL_PATH)))){$anchor->setAttribute('href',wp_get_attachment_url($entry['id']));break;}}}
    foreach($xp->query('//*[@href or @action]') as $node)foreach(['href','action'] as $attr)if($node->hasAttribute($attr))$node->setAttribute($attr,cb_local_url($node->getAttribute($attr)));
    foreach($xp->query('//form[contains(@class,"wpcf7-form")]') as $form){$form->setAttribute('action',admin_url('admin-post.php'));$form->setAttribute('method','post');$form->removeAttribute('aria-label');foreach(['action'=>'cb_contact','_cb_nonce'=>wp_create_nonce('cb_contact')] as $name=>$value){$input=$doc->createElement('input');$input->setAttribute('type','hidden');$input->setAttribute('name',$name);$input->setAttribute('value',$value);$form->appendChild($input);}foreach($xp->query('.//input[@type="checkbox"]',$form) as $checkbox)$checkbox->setAttribute('name','cb_consent');$note=$doc->createElement('p','Formularz lokalny: wiadomość zostanie zapisana w środowisku testowym; nie jest wysyłana do uczelni.');$note->setAttribute('class','cb-form-note');$form->appendChild($note);}
    foreach($xp->query('//input[not(@type="hidden") and not(@type="submit")]|//textarea|//select') as $input){$name=$input->getAttribute('name');if(!$input->getAttribute('aria-label'))$input->setAttribute('aria-label',$input->getAttribute('placeholder')?:$name);if($input->getAttribute('aria-required')==='true')$input->setAttribute('required','required');$input->removeAttribute('disabled');}
    $root=$doc->getElementById('cb-import-root');$out='';foreach($root->childNodes as $node)$out.=$doc->saveHTML($node);return $out;
}
function cb_import_values($value,$key=''){if(!is_array($value))return in_array($key,['body','shell','title'],true)?cb_import_html((string)$value):$value;foreach($value as $k=>$v)$value[$k]=cb_import_values($v,$k);if(isset($value['body'])){if(preg_match('/data-cb-attachment="(\d+)"/',$value['body'],$match))$value['image']=(int)$match[1];if(preg_match('/<a[^>]*href="([^"]+)"[^>]*>/',$value['body'],$match))$value['link']=['url'=>html_entity_decode($match[1]),'title'=>strip_tags($value['body']),'target'=>''];}return $value;}
foreach($data['pages'] as $p){$meta=['title'=>$p['seoTitle']??$p['title'],'description'=>''];foreach($p['seo'] as $m)if($m['name']==='description')$meta['description']=$m['content'];
    if($p['id']==='CB-02'){update_option('cb_archive_sections',cb_import_values($p['sections']),false);update_field('field_cb_sections',cb_import_values($p['sections']),'option');update_option('cb_archive_breadcrumb',cb_import_html($p['breadcrumb']),false);update_option('cb_archive_seo',$meta,false);update_option('cb_archive_source_metadata',$p['seo'],false);$archive=new DOMDocument();libxml_use_internal_errors(true);$archive->loadHTML('<?xml encoding="UTF-8">'.$p['html']);$archive_xpath=new DOMXPath($archive);$pagination=$archive_xpath->query('//nav[contains(@class,"pagination")]')->item(0);update_option('cb_archive_pagination',$pagination?cb_import_html($archive->saveHTML($pagination)):'',false);$category_order=[];foreach($archive_xpath->query('//div[contains(@class,"categories")]//a[@href]') as $link){$slug=basename(wp_parse_url($link->getAttribute('href'),PHP_URL_PATH));$category_order[]=$slug;$term=get_term_by('slug',$slug,'category');if($term)wp_update_term($term->term_id,'category',['name'=>trim($link->textContent)]);else wp_insert_term(trim($link->textContent),'category',['slug'=>$slug,'parent'=>$root]);}update_option('cb_archive_category_order',$category_order,false);$search=$archive_xpath->query('//div[contains(@class,"search-box")]//form')->item(0);if($search){$search->setAttribute('action',home_url('/'));foreach($archive_xpath->query('.//input[@name="id"]',$search) as $input)$input->parentNode->removeChild($input);update_option('cb_archive_search',cb_import_html($archive->saveHTML($search)),false);}continue;}
    $id=$ids[$p['id']];update_field('field_cb_leading_space',(int)$p['leadingSpace'],$id);update_post_meta($id,'_cb_breadcrumb',cb_import_html($p['breadcrumb']));$sections=cb_import_values($p['sections']);update_field('field_cb_sections',$sections,$id);update_post_meta($id,'_cb_seo',$meta);update_post_meta($id,'_cb_source_metadata',$p['seo']);update_post_meta($id,'_yoast_wpseo_title',$meta['title']);update_post_meta($id,'_yoast_wpseo_metadesc',$meta['description']);
    if($p['id']==='CB-03')wp_update_post(['ID'=>$id,'post_content'=>$sections[0]['body']]);
    WP_CLI::log($p['id'].' -> '.$id.' '.get_permalink($id));
}
// Native cards: only actual captured summaries. Full CB-03 remains the only required single article.
$cards=[];foreach($data['pages'] as $p)foreach($p['cards'] as $card)if(strpos($card['url'],'/wpisy/')!==false && ($p['id']==='CB-02'||!isset($cards[$card['url']])))$cards[$card['url']]=$card;
foreach($cards as $card){$path=wp_parse_url($card['url'],PHP_URL_PATH);if(isset($urlmap[$path]))continue;$slug=basename($path);$id=cb_import_record($card['url'],'post',$slug,$card['title']);$bits=explode('/',trim($path,'/'));$category=$bits[1]??'blog-post';$term=get_term_by('slug',$category,'category');if(!$term){$made=wp_insert_term(ucfirst($category),'category',['slug'=>$category,'parent'=>$root]);$term=get_term($made['term_id']);}wp_set_post_categories($id,[$term->term_id]);
    $date=DateTime::createFromFormat('!d/m/Y',$card['date']);if(!$date)throw new RuntimeException('Missing captured publication date: '.$card['url']);wp_update_post(['ID'=>$id,'post_excerpt'=>wp_strip_all_tags($card['excerpt']),'post_date'=>$date->format('Y-m-d').' 12:00:00']);update_post_meta($id,'_cb_reference_only',$card['url']);update_post_meta($id,'_cb_card_html',cb_import_html($card['html']));if(isset($assets[$card['image']]))set_post_thumbnail($id,$assets[$card['image']]['id']);
}
foreach($cards as $card){$found=get_posts(['post_type'=>'post','meta_key'=>'_cb_source_url','meta_value'=>$card['url'],'numberposts'=>1]);if($found){$date=DateTime::createFromFormat('!d/m/Y',$card['date']);if(!$date)throw new RuntimeException('Missing captured publication date: '.$card['url']);wp_update_post(['ID'=>$found[0]->ID,'post_excerpt'=>wp_strip_all_tags($card['excerpt']),'post_date'=>$date->format('Y-m-d').' 12:00:00']);update_post_meta($found[0]->ID,'_cb_card_html',cb_import_html($card['html']));if(isset($assets[$card['image']]))set_post_thumbnail($found[0]->ID,$assets[$card['image']]['id']);}}
// Prefer the original article's precise publication timestamp over card-only dates.
foreach($data['pages'] as $page)if($page['id']==='CB-03')foreach($page['seo'] as $meta)if($meta['name']==='article:published_time'){
    $published=new DateTimeImmutable($meta['content']);$timestamp=$published->getTimestamp();wp_update_post(['ID'=>$ids['CB-03'],'post_date'=>wp_date('Y-m-d H:i:s',$timestamp,wp_timezone()),'post_date_gmt'=>gmdate('Y-m-d H:i:s',$timestamp)]);
}
$article=$ids['CB-03'];if(preg_match('/data-cb-attachment="(\d+)"/',get_post_field('post_content',$article),$featured))set_post_thumbnail($article,(int)$featured[1]);
foreach($cards as $card){$posts=get_posts(['post_type'=>'post','meta_key'=>'_cb_source_url','meta_value'=>$card['url'],'numberposts'=>1]);if($posts)update_post_meta($posts[0]->ID,'_cb_imported_thumbnail_id',get_post_thumbnail_id($posts[0]->ID));}
$home=$data['pages'][0];$header=cb_import_html($home['header']);$doc=new DOMDocument();libxml_use_internal_errors(true);$doc->loadHTML('<?xml encoding="UTF-8"><div id="root">'.$header.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);$xp=new DOMXPath($doc);$menu=$xp->query('//*[contains(concat(" ",normalize-space(@class)," ")," main-menu ")]')->item(0);while($menu->firstChild)$menu->removeChild($menu->firstChild);$menu->appendChild($doc->createTextNode('[cb_navigation]'));$menu->setAttribute('id','cb-navigation');$menu->setAttribute('role','navigation');$menu->setAttribute('aria-label','Nawigacja główna');$button=$xp->query('//button[contains(@class,"hamburger")]')->item(0);$button->setAttribute('aria-controls','cb-navigation');$button->setAttribute('aria-expanded','false');$button->setAttribute('aria-label','Otwórz menu');$header='';foreach($doc->getElementById('root')->childNodes as $node)$header.=$doc->saveHTML($node);
update_option('cb_header',$header,false);update_option('cb_footer',cb_import_html($home['footer']),false);update_field('field_cb_header',$header,'option');update_field('field_cb_footer',cb_import_html($home['footer']),'option');
$menu=wp_get_nav_menu_object('Collegium Balticum');$menu_id=$menu?$menu->term_id:wp_create_nav_menu('Collegium Balticum');
function cb_import_menu($items,$menu,$parent=0){foreach($items as $index=>$item){$key=hash('sha256',$parent.'|'.$item['url'].'|'.$item['title']);$found=get_posts(['post_type'=>'nav_menu_item','post_status'=>'any','meta_key'=>'_cb_menu_key','meta_value'=>$key,'numberposts'=>1]);$id=wp_update_nav_menu_item($menu,$found?$found[0]->ID:0,['menu-item-title'=>wp_kses_post($item['title_html']??$item['title']),'menu-item-classes'=>implode(' ',$item['classes']??[]),'menu-item-url'=>cb_local_url($item['url']),'menu-item-type'=>'custom','menu-item-status'=>'publish','menu-item-parent-id'=>$parent,'menu-item-position'=>$index+1]);update_post_meta($id,'_cb_menu_key',$key);cb_import_menu($item['children'],$menu,$id);}}
cb_import_menu($home['menu'],$menu_id);$locations=get_theme_mod('nav_menu_locations',[]);$locations['header']=$menu_id;set_theme_mod('nav_menu_locations',$locations);
update_option('show_on_front','page');update_option('page_on_front',$ids['CB-00']);update_option('page_for_posts',0);update_option('permalink_structure','/%category%/%postname%/');update_option('posts_per_page',6);update_option('blog_public',0);update_option('blogname','Collegium Balticum');update_option('cb_migration',1,false);update_option('cb_import_origin',home_url(),false);flush_rewrite_rules();
file_put_contents($cache.'/import-result.json',wp_json_encode(['ids'=>$ids,'urls'=>$urlmap,'media'=>count($assets),'missing'=>array_merge($missing,$GLOBALS['cb_import_missing']),'posts'=>count($cards),'mediaAttachments'=>count(array_unique(array_column($assets,'id'))),'runtime'=>['theme'=>get_stylesheet(),'acf'=>defined('ACF_VERSION')?ACF_VERSION:null,'environment'=>wp_get_environment_type(),'localUrl'=>home_url(),'locale'=>get_locale(),'blogPublic'=>get_option('blog_public'),'counts'=>array_map(function($type){return (int)array_sum((array)wp_count_posts($type));},['page','post','attachment','nav_menu_item'])],'time'=>gmdate('c')],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));WP_CLI::success('Imported all 19 required views; media URLs '.count($assets).'; missing '.count($missing));
