/** Separate PM preview only: stylesheet injected in ephemeral Playwright pages, never WP. */
const fs=require('fs'),path=require('path'),{getChromium,discoverBrowser}=require('../../../factory/qa/browser');
const cache=path.resolve(__dirname,'../../../../.factory-cache/live/collegium-balticum/migration');
function luminance(hex){const c=hex.replace('#','').match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;}
function contrast(a,b){const [hi,lo]=[luminance(a),luminance(b)].sort((a,b)=>b-a);return(hi+.05)/(lo+.05);}
async function main(){const b=await getChromium().launch({executablePath:discoverBrowser().browser.executablePath,args:['--no-sandbox']});const rows=[];const audits=JSON.parse(fs.readFileSync(path.join(cache,'task4f/audit-after.json'))).rows;
for(const r of audits.filter(r=>['CB-01','CB-03','CB-04'].includes(r.id))){const p=await b.newPage({viewport:r.view==='desktop'?{width:1440,height:900}:{width:390,height:844},deviceScaleFactor:1,reducedMotion:'reduce'});await p.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());const pageRecord=JSON.parse(fs.readFileSync(path.join(cache,'source.json'))).pages.find(x=>x.id===r.id);await p.goto('http://localhost:8000'+pageRecord.path,{waitUntil:'domcontentloaded'});await p.evaluate(async()=>{await document.fonts.ready;document.querySelectorAll('img').forEach(i=>i.loading='eager');await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));});
const selectors=r.axe.violations.filter(v=>['color-contrast','link-in-text-block'].includes(v.id)).flatMap(v=>v.nodes.flatMap(n=>n.target)).filter(t=>typeof t==='string');
const css=selectors.map(s=>'html body.cb-site '+s+'{color:#03294b!important;opacity:1!important;}').join('\n')+'\nhtml body.cb-site main p a{ text-decoration:underline!important; }html body.cb-site .breadcrumbs,html body.cb-site .breadcrumbs a,html body.cb-site .cb-header a,html body.cb-site .cb-header a span,html body.cb-site .cb-footer a{color:#03294b!important;opacity:1!important;}';
await p.screenshot({path:path.join(cache,'task4f',r.id+'-'+r.view+'-pm-current.png'),fullPage:true});await p.addStyleTag({content:css});await p.screenshot({path:path.join(cache,'task4f',r.id+'-'+r.view+'-pm-aa-candidate.png'),fullPage:true});const currentFile=path.join(cache,'task4f',r.id+'-'+r.view+'-pm-current.png'),candidateFile=path.join(cache,'task4f',r.id+'-'+r.view+'-pm-aa-candidate.png');
const pair=await p.evaluate(async({a,b})=>{const load=async src=>{const i=new Image;i.src=src;await i.decode();return i};const [x,y]=await Promise.all([load(a),load(b)]),c=document.createElement('canvas');c.width=Math.max(x.width,y.width)*2;c.height=Math.max(x.height,y.height);const context=c.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,c.width,c.height);context.drawImage(x,0,0);context.drawImage(y,c.width/2,0);return c.toDataURL().split(',')[1]},{a:'data:image/png;base64,'+fs.readFileSync(currentFile).toString('base64'),b:'data:image/png;base64,'+fs.readFileSync(candidateFile).toString('base64')});fs.writeFileSync(path.join(cache,'task4f',r.id+'-'+r.view+'-pm-pair.png'),Buffer.from(pair,'base64'));
await p.addScriptTag({path:require.resolve('axe-core/axe.min.js')});const after=await p.evaluate(async()=>{const a=await axe.run(document,{runOnly:{type:'rule',values:['color-contrast','link-in-text-block']}});return{violations:a.violations,incomplete:a.incomplete};});rows.push({id:r.id,view:r.view,css,after});await p.close();}await b.close();fs.writeFileSync(path.join(cache,'task4f/aa-variant.json'),JSON.stringify({status:'PROPOSAL_ONLY_NOT_APPLIED',candidate:'#03294b text on unchanged source backgrounds; underlined body links',contrasts:['#ea8314','#00aeef','#ffffff'].map(background=>({foreground:'#03294b',background,ratio:contrast('#03294b',background)})),rows},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
