services:

  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu-24.04
    command: sleep infinity

    volumes:
      - ..:/workspace:cached

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp

    depends_on:
      - db

  db:
    image: mysql:8.0

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp

    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: