const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),http=require('http');
const {run,homeReady}=require('./run');
const {importBundle}=require('./import');
const {verify,zip,unzip,sha}=require('../../../../tools/live-capture/bundle');
const {discoverBrowser,getChromium}=require('../../../factory/qa/browser');
const config=require('../../../../docs/projects/collegium-balticum/live.json');
test('PoC gates full batch, saves real browser fixtures/HTML/assets, retry validates prior proof, ZIP rejects tampering',async()=>{
  const temp=fs.mkdtempSync(path.join(os.tmpdir(),'cb-remote-test-'));let blocked=false;const requests=[];
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
  const server=http.createServer((req,res)=>{requests.push(req.url);if(req.url==='/style.css'){res.setHeader('content-type','text/css');res.end('body{font-family:Arial;color:#222}main{max-width:1100px;margin:auto;min-height:1100px}');return;}if(req.url==='/image.png'){res.setHeader('content-type','image/png');res.end(png);return;}res.setHeader('content-type','text/html');if(blocked){res.end('<html><title>One moment, please</title><body>Please wait while your request is being verified</body></html>');return;}res.end('<!doctype html><html lang="pl"><head><meta name="viewport" content="width=device-width, initial-scale=1"><title>Collegium Balticum — TEST FIXTURE ONLY</title><link rel="stylesheet" href="/style.css"><meta name="description" content="Test fixture, not CB reference"></head><body><header>Test menu</header><main><h1>Collegium Balticum — jawna strona kontrolna</h1><p>'+('Treść kontrolna nie jest rzeczywistą treścią CB. '.repeat(12))+'</p><section><h2>Kontrolna sekcja</h2><img src="/image.png" alt="Grafika testowa"><a href="/other/">Kontrolny link</a></section></main><footer>Test footer</footer></body></html>');});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const source={...config,sourceUrl:'http://127.0.0.1:'+server.address().port,timeoutMs:3000,settleMs:0,routes:[{id:'CB-00',path:'/'},{id:'CB-01',path:'/other/'}],viewports:config.viewports.filter(v=>['desktop','mobile'].includes(v.id))};
  const browser=await getChromium().launch({executablePath:discoverBrowser().browser.executablePath,headless:true,args:['--no-sandbox']});
  try{
    const output=path.join(temp,'home'),m=await run({mode:'home',output,source,browser});assert.equal(m.status,'DONE');assert.ok(homeReady(m.records));assert.equal(m.records.length,2);assert.ok(m.records.every(r=>r.identity.h1.length===1&&r.identity.css[0].loaded&&r.identity.fonts.ready));verify(output,source);assert.ok(m.files.some(f=>f.path.startsWith('assets/')));
    const unpacked=path.join(temp,'unpacked');unzip(output+'.zip',unpacked);verify(unpacked,source);
    fs.appendFileSync(path.join(unpacked,m.records[0].paths.html),'changed');assert.throws(()=>verify(unpacked,source),/HASH_MISMATCH/);
    blocked=true;requests.length=0;const failure=await run({mode:'full',output:path.join(temp,'blocked'),source,browser});assert.equal(failure.status,'BLOCKED');assert.equal(failure.records.length,1);assert.ok(!requests.includes('/other/'));assert.ok(!failure.files.some(f=>f.path.endsWith('/full.png')));
    blocked=false;const full=await run({mode:'full',output:path.join(temp,'full'),source,browser});assert.equal(full.records.length,4);assert.equal(full.status,'DONE');const imports=path.join(temp,'imports');const imported=importBundle(path.join(temp,'full.zip'),{source,importRoot:imports});assert.equal(importBundle(path.join(temp,'full.zip'),{source,importRoot:imports}),imported);const index=JSON.parse(fs.readFileSync(path.join(imports,'references-index.json')));assert.equal(index.rows.length,2);assert.ok(index.rows.every(r=>r.SOURCE_CAPTURE==='DONE'&&r.VISUAL_QA==='NOT_STARTED'));assert.throws(()=>importBundle(path.join(temp,'full.zip'),{source,importRoot:imports,githubArtifact:{workflow_run:{id:123,head_sha:'bad'}}}),/PROVENANCE/);
    const retry=await run({mode:'retry',previous:path.join(temp,'full'),output:path.join(temp,'retry'),source,browser});assert.equal(retry.records.length,0,'No successful routes repeated');assert.equal(retry.status,'DONE');
    const archive=fs.readFileSync(output+'.zip');const bad=Buffer.from(archive);let start=bad.indexOf(Buffer.from('https-probe.json'));assert.ok(start>0);Buffer.from('../evil-file.txt').copy(bad,start,0,15);fs.writeFileSync(path.join(temp,'bad.zip'),bad);assert.throws(()=>unzip(path.join(temp,'bad.zip'),path.join(temp,'bad')),/UNSAFE_PATH|ZIP|HEADER/);
    // GitHub artifact ZIPs can have a ZIP64 footer even for a small bundle.
    const end=archive.length-22,offset=archive.readUInt32LE(end+16),count=archive.readUInt16LE(end+10),z=Buffer.alloc(56),locator=Buffer.alloc(20),footer=Buffer.from(archive.subarray(end));z.writeUInt32LE(0x06064b50);z.writeBigUInt64LE(44n,4);z.writeUInt16LE(45,12);z.writeUInt16LE(45,14);z.writeBigUInt64LE(BigInt(count),24);z.writeBigUInt64LE(BigInt(count),32);z.writeBigUInt64LE(BigInt(end-offset),40);z.writeBigUInt64LE(BigInt(offset),48);locator.writeUInt32LE(0x07064b50);locator.writeBigUInt64LE(BigInt(end),8);locator.writeUInt32LE(1,16);footer.writeUInt16LE(65535,8);footer.writeUInt16LE(65535,10);footer.writeUInt32LE(0xffffffff,16);fs.writeFileSync(path.join(temp,'zip64.zip'),Buffer.concat([archive.subarray(0,end),z,locator,footer]));unzip(path.join(temp,'zip64.zip'),path.join(temp,'zip64'));verify(path.join(temp,'zip64'),source);
    console.log('LOCAL FIXTURE ONLY: no CB references produced');
  }finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true});}
});
