// Caller authentication stays in the local environment; no token is put into artifacts/workflows.
const fs=require('fs'),path=require('path');
const {importBundle}=require('./import');
const repo='marcinpracavp/mwstudios-wordpress-factory';
const token=process.env.GH_TOKEN||process.env.GITHUB_TOKEN||process.env.GITHUB_CODESPACE_TOKEN;
async function api(suffix,options={}){const r=await fetch('https://api.github.com/repos/'+repo+'/'+suffix,{...options,headers:{Accept:'application/vnd.github+json','User-Agent':'CB-LIVE-capture',...(token?{Authorization:'Bearer '+token}:{}),...options.headers}});if(!r.ok)throw Error('GitHub HTTP '+r.status+': '+(await r.text()).slice(0,300));return r.status===204?null:r.json();}
async function main(args){const [command,value]=args;
  if(command==='runs'){console.log(JSON.stringify(await api('actions/workflows/cb-capture.yml/runs?branch=project%2Fcollegium-balticum&per_page=5'),null,2));}
  else if(command==='dispatch'){if(!['home','full','retry'].includes(value))throw Error('Mode required');const inputs={mode:value};if(value==='retry'){const mapping=JSON.parse(fs.readFileSync(args[2]));inputs.failed_ids=mapping.rows.filter(r=>r.SOURCE_CAPTURE==='BLOCKED').map(r=>r.id).join(',');if(!inputs.failed_ids)throw Error('NO_FAILED_ROUTES');}await api('actions/workflows/cb-capture.yml/dispatches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:'project/collegium-balticum',inputs})});console.log('Workflow dispatched: '+value);}
  else if(command==='download'){if(!/^\d+$/.test(value||''))throw Error('Artifact ID required');const metadata=await api('actions/artifacts/'+value);if(metadata.expired||!metadata.name.startsWith('cb-live-')||!metadata.workflow_run)throw Error('WRONG_ARTIFACT');const r=await fetch('https://api.github.com/repos/'+repo+'/actions/artifacts/'+value+'/zip',{redirect:'manual',headers:{Accept:'application/vnd.github+json','User-Agent':'CB-LIVE-capture',...(token?{Authorization:'Bearer '+token}:{})}});if(r.status!==302)throw Error('Artifact download HTTP '+r.status);const location=r.headers.get('location');if(!location||new URL(location).protocol!=='https:')throw Error('UNSAFE_DOWNLOAD_URL');const response=await fetch(location,{signal:AbortSignal.timeout(120000)});if(!response.ok)throw Error('Download failed');const bytes=Buffer.from(await response.arrayBuffer());if(bytes.length>512*1024*1024)throw Error('ARTIFACT_TOO_LARGE');const root=path.resolve('.factory-cache/live/collegium-balticum/downloads');fs.mkdirSync(root,{recursive:true});const file=path.join(root,value+'.zip');if(fs.existsSync(file)&&!fs.readFileSync(file).equals(bytes))throw Error('DOWNLOAD_ALREADY_EXISTS_DIFFERENT');fs.writeFileSync(file,bytes);importBundle(file,{githubArtifact:metadata});}
  else throw Error('Usage: github.js runs | dispatch home/full | dispatch retry <import.json> | download <artifact-id>');
}
if(require.main===module)main(process.argv.slice(2)).catch(error=>{console.error(error.message);process.exitCode=1;});
module.exports={api,main};
